services:
  - type: web
    name: maidease-api
    runtime: python
    pythonVersion: 3.10
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DEBUG
        value: "True"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: DATABASE_URL
        sync: postgresql://postgres:Miadease123rko@db.euxqikjnazjetymepkke.supabase.co:5432/postgres
      - key: SECRET_KEY
        sync: ZXyO1NFtQQvd6uAsSyLwwEQUFbTg9YWjoEKARP3D90M
      - key: CORS_ORIGINS
        value: "http://localhost:5173"
